version: 2
updates:
- package-ecosystem: terraform
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: UTC
  open-pull-requests-limit: 5
  commit-message:
    prefix: build
    include: scope
- package-ecosystem: terraform
  directory: "/three"
  schedule:
    interval: daily
    time: "09:00"
    timezone: UTC
  open-pull-requests-limit: 5
  commit-message:
    prefix: build
    include: scope
